### ISSUE TITLE
Rebuild landing page with Astro

### ISSUE THREAD

**Issue by adwinying** [adwinying/todo#2]
[Astro](https://astro.build/) allows you to generate HTML with existing JS SPA frameworks (React, Preact, Svelte, Vue) while shipping zero JS. 

Replacing handlebars.js-powered landing page with Astro: https://github.com/adwinying/adwinying.github.io/tree/v4

### Todo
- [x] Initialize astro project
- [x] Initialize tailwindcss
- [x] Initialize ESlint
- [x] Rebuild partials into components
  - [x] Hero
  - [x] Nav desktop
  - [x] Nav mobile
  - [x] About
  - [x] Skills
  - [x] Projects
  - [x] Connect
  - [x] Footer
- [x] Mobile display optimization
- [x] Restore JS-powered interactivity
  - [x] Smooth scrolling
  - [x] Animate section title on scroll
  - [x] Nav menu toggle
- [x] Restore 404 Page
- [x] Reconfigure CD
