### ISSUE TITLE
Try out nixOS

### ISSUE THREAD

**Issue by adwinying** [adwinying/todo#32]
https://www.reddit.com/r/NixOS/comments/11kme1n/combining_traditional_dotfiles_and_nixos/

## TODO
- [x] Basic config
- [x] init dotfiles git repo
- [x] copilot CLI
- [x] migrate bootes
- [x] laravel devshell
- [x] replace .profile source with direnv
- [x] show in prompt when devenv is activated
- [x] configure ssh private keys
- [x] server provision migrate
- [x] ~~lima image~~ ~~[qemu](https://github.com/adwinying/macos-libvirt)~~ UTM VM
- [x] update [devcontainer](https://github.com/adwinying/devcontainer)
- [x] custom ISO?
- [ ] disko?

**Comment by adwinying** [comment]
nixOS install in 3 mins: https://asciinema.org/a/581903
