### ISSUE TITLE
Migrate some services from local server to the cloud

### ISSUE THREAD

**Issue by adwinying** [adwinying/todo#4]
Oracle cloud's free tier is quite generous
https://www.oracle.com/cloud/free/

Planning to move somewhat critical services to a more reliable server (´ω`)

### Todo
- [x] Set up cloud instance
- [x] Configure cloud instance
  - [x] Install docker
  - [x] Configure docker
  - [x] Configure load balancer
- [x] Update and test DNS settings
- [x] Set up backup
- [x] Commit configs to git
- [x] Configure docker auto update

**Comment by adwinying** [comment]
Completed and automated with ansible
https://github.com/takoandpancake/ansible
